version: '3.8'

services:
  stock-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-api
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - GIN_MODE=release
    networks:
      - stock-network

networks:
  stock-network:
    driver: bridge


